### ISSUE TITLE
Context?

### ISSUE THREAD

**Issue by unhandyandy** [Ludeme/LudiiExampleAI#5]
Is the Context class documented anywhere, or is the code viewable?  Seems like that would be useful for writing custom AI.

**Comment by Ludeme** [comment]
Source code and javadoc are not publicly available for that class. For this specific class we can privately send you the current .java file, but we prefer not to post it publicly because it may become outdated. Feel free to send us a mail at `ludii.games@gmail.com` and we'll send it back to you.

**Comment by unhandyandy** [comment]
OK, but some of the Context methods are necessary for the AI:
```
game.moves(context).moves()
context.game();
context.trial();
context.state();
if (trial.over() || !context.active(maximisingPlayer))

```
It would be nice to understand what exactly `trial`, `state`, and `maximisingPlayer` are.

**Comment by DennisSoemers** [comment]
[This tutorial](https://ludiitutorials.readthedocs.io/en/latest/ludii_terminology.html) should be able to at least provide some high-level intuition about some of those classes. There are also some other tutorials, and example code in some of our different repos, which can hopefully give some insight into the different methods that are available in these classes. Unfortunately I can't provide you with anything more concrete now.

The `maximisingPlayer` thing is just a local variable specific to the AlphaBeta code by the way. In the vast majority of cases, it's really just the index of the player whom you're running the tree search for. Only in games with a Swap rule can this sometimes be different -- this thing is intended to make sure that perspectives from which heuristic evaluations are performed also properly swaps around when players swap roles somewhere in the middle of a tree search.

**Comment by unhandyandy** [comment]
Ah, that helps, thanks.  Maybe that info should be included in the Language Reference.

**Comment by unhandyandy** [comment]
But surely the State class needs to be thoroughly documented in order for custom evaluators to be written?

**Comment by cambolbro** [comment]
Documenting the State class is not an easy task, there are 20 subclasses derived from it for the various game types we support, plus dozens of support classes that they require... But we are working on a _Ludii Game Logic Guide_ that will give more details into how the game logic interacts with the game states, which should be helpful for understanding how the state representation works. This is currently being written and should be ready in October.

**Comment by unhandyandy** [comment]
OK, I'll look for that - I have to at least know how positions are represented before I can think about writing a custom AI.
